from typing import Any, Protocol


class UserRepository(Protocol):
    def find_by_id(self, user_id: str) -> dict[str, Any] | None: ...

    def find_by_email(self, email: str) -> dict[str, Any] | None: ...

    def find_by_phone_number(self, phone_number: str) -> dict[str, Any] | None: ...

    def insert(self, doc: dict[str, Any]) -> None: ...

    def update(self, user_id: str, updates: dict[str, Any]) -> bool: ...

    def delete(self, user_id: str) -> bool: ...

    def list_by_ids(self, user_ids: list[str]) -> list[dict[str, Any]]: ...

    def list_paginated(self, *, skip: int, limit: int) -> list[dict[str, Any]]: ...

    def count(self) -> int: ...


class OrganizationRepository(Protocol):
    def find_by_id(self, org_id: str) -> dict[str, Any] | None: ...

    def find_by_slug(self, slug: str) -> dict[str, Any] | None: ...

    def insert(self, doc: dict[str, Any]) -> None: ...

    def update(self, org_id: str, updates: dict[str, Any]) -> bool: ...

    def delete(self, org_id: str) -> bool: ...

    def list_by_ids(self, org_ids: list[str]) -> list[dict[str, Any]]: ...

    def list_paginated(self, *, skip: int, limit: int) -> list[dict[str, Any]]: ...

    def count(self) -> int: ...


class MembershipRepository(Protocol):
    def find(self, organization_id: str, user_id: str) -> dict[str, Any] | None: ...

    def insert(self, doc: dict[str, Any]) -> None: ...

    def update_role(self, organization_id: str, user_id: str, role: str) -> bool: ...

    def delete(self, organization_id: str, user_id: str) -> bool: ...

    def list_by_organization(self, organization_id: str) -> list[dict[str, Any]]: ...

    def list_by_user(self, user_id: str) -> list[dict[str, Any]]: ...

    def delete_by_organization(self, organization_id: str) -> int: ...

    def delete_by_user(self, user_id: str) -> int: ...


class AuthTokenRepository(Protocol):
    def find_by_token_hash(self, token_hash: str) -> dict[str, Any] | None: ...

    def insert(self, doc: dict[str, Any]) -> None: ...

    def delete(self, token_hash: str) -> bool: ...

    def delete_by_user(self, user_id: str) -> int: ...
