# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Src/Server.WebAPI/Server.WebAPI.csproj", "Src/Server.WebAPI/"]
RUN dotnet restore "./Src/Server.WebAPI/Server.WebAPI.csproj"
COPY . .
WORKDIR "/src/Src/Server.WebAPI"
RUN dotnet build "./Server.WebAPI.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Server.WebAPI.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
# Use non-root user if running in containerized environment where $APP_UID might not be set
# ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "Server.WebAPI.dll"]